# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        example-node-project: ["example-projects/frontend/vue-frontend", "example-projects/frontend/vue-frontend", "example-projects/backend/node-backend"]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ matrix.example-node-project }}/package-lock.json
    - run: npm ci
      working-directory: ${{ matrix.example-node-project }}
    - run: npm run build --if-present
      working-directory: ${{ matrix.example-node-project }}
    - run: npm test
      working-directory: ${{ matrix.example-node-project }}
